version: "3.7"

services:
  devsqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest 
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - /docker/appdata/sqlserver/data:/var/opt/mssql/data 
    restart: unless-stopped