version: '3.7'

services:
    homeassistant:
      container_name: homeassistant
      image: "ghcr.io/home-assistant/home-assistant:stable"
      ports:
      - "8123:8123"
      volumes:
        - /docker/appdata/homeassistant/config:/config
        - /etc/localtime:/etc/localtime:ro
        - /run/dbus:/run/dbus:ro
      restart: unless-stopped
      privileged: true

    netdaemon:
      container_name: netdaemon4
      image: netdaemon/netdaemon4
      restart: unless-stopped
      environment:
        - HomeAssistant__Host=${HomeAssistant__Host}
        - HomeAssistant__Token=${HomeAssistant__Token}
        - NetDaemon__ApplicationAssembly=NetDaemon.dll
        - Logging__LogLevel__Default=${Logging__LogLevel__Default}
        - TZ=${TZ}
      volumes:
        - /docker/appdata/netdaemon:/data